# Generated by Django 5.0.6 on 2024-07-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_usermodel_password_alter_usermodel_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='password',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='username',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='image',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to='users/images/'),
        ),
    ]
