# Generated by Django 5.0.6 on 2024-07-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_usermodel_email_alter_usermodel_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(default='user@example.com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='image',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to='users/images/'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(default='defaultpassword', max_length=128),
        ),
    ]
