# Generated by Django 5.0.6 on 2024-07-13 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_alter_pet_breed_alter_pet_color_alter_pet_sex_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='owner',
        ),
        migrations.AddField(
            model_name='pet',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pet',
            name='color',
            field=models.CharField(choices=[('black', 'Black'), ('white', 'White'), ('brown', 'Brown'), ('grey', 'Grey'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(upload_to='pet_images/'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='size',
            field=models.CharField(choices=[('tiny', 'Tiny (<5kg)'), ('small', 'Small (5-10kg)'), ('medium', 'Medium (10-15kg)'), ('large', 'Large (15-30kg)'), ('very_large', 'Very Large (>30kg)'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('rabbit', 'Rabbit'), ('other', 'Other')], max_length=20),
        ),
    ]
