# Generated by Django 5.0.6 on 2024-07-13 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_alter_pet_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='created_by',
        ),
    ]
