# Generated by Django 5.0.6 on 2024-07-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0005_remove_pet_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(choices=[('Labrador', 'Labrador'), ('Persian', 'Persian')], max_length=100),
        ),
    ]
