# Generated by Django 5.0.6 on 2024-07-14 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0012_alter_pet_breed_alter_pet_color_alter_pet_sex_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='status',
            new_name='statusPet',
        ),
    ]
