# Generated by Django 5.0.6 on 2024-07-14 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0013_rename_status_pet_statuspet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='statusPet',
            new_name='status',
        ),
    ]
