# Generated by Django 5.0.6 on 2024-07-14 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0001_initial'),
        ('pet', '0012_alter_pet_breed_alter_pet_color_alter_pet_sex_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status',
            new_name='statusPet',
        ),
    ]
