# Generated by Django 5.0.6 on 2024-07-14 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0002_rename_status_statuspet'),
        ('pet', '0014_rename_statuspet_pet_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='statusPet',
            new_name='Status',
        ),
    ]
