# Generated by Django 5.0.6 on 2024-07-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0003_rename_statuspet_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sex',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
